version: '2.4'

services:
  postgres:
    container_name: postgres
    build: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:

volumes:
  db:
